server:
  port: 8091

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    #url: jdbc:oracle:thin:@43.200.33.166:1522/xe
    #url: jdbc:oracle:thin:@192.168.0.24:1522/xe
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: YOUNGLEE
    password: YOUNGLEE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/productimgs/

  #swagger2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# ??? ??? ??? ??? ? ??? ?? ??
image:
  # WebConfig? ??
  #add-resource-locations: classpath:/static/productimgs/
  #add-resource-handler: /productimgs/**

  add-resource-locations: /productimgs/
  add-resource-handler: /productimgs/**


  # ProductService? ??
  #image-dir: src/main/resources/static/productimgs/
  image-dir: /productimgs/
  #image-url: http://43.200.33.166:8090/productimgs/
  #image-url: http://192.168.0.24:8090/productimgs/
  image-url: http://localhost:8090/productimgs/

# HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ??
# Secret ?? ?? ???? Base64 ? ???? ? ??
jwt:
  secret: dW5pLXJlYWN0LW5naW54LXNwcmluZy1ib290LWp3dC1vcmFjbGUtZG9ja2VyLWVjMi1yZWFjdC1uZ25peC1zcHJpbmctYm9vdC1qd3Qtb3JhY2xlLWRvY2tlci1lYzIK


mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/*.xml
  # alias Setting
  type-aliases-package: com.uni.practice
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info


